include(ExternalProject)

set(TAGLIB_REPO_URL https://github.com/taglib/taglib)
set(TAGLIB_TAG v1.11)

set(TAGLIB_CMAKE_ARGS
   ${COMMON_CMAKE_ARGS}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}
    -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
#    -DENABLE_STATIC_RUNTIME=ON
#    -DVISIBILITY_HIDDEN=ON
    -DWITH_ASF=ON
    -DWITH_MP4=ON
#   -DWITH_64BIT=ON
)

externalproject_add(taglib
    DEPENDS zlib
    GIT_REPOSITORY  ${TAGLIB_REPO_URL}
    GIT_TAG         ${TAGLIB_TAG}
    CMAKE_ARGS      ${TAGLIB_CMAKE_ARGS}
 )
