language: cpp
sudo: false
compiler:
- gcc
addons:
  apt:
    packages:
    - coreutils
    - realpath    
    - wget
    - zip
    - build-essential
    - mingw-w64
    - g++-mingw-w64
before_script: build/build_deps
script: build/build_release
deploy:
  provider: releases
  api_key:
    secure: KFr3snZO7b0uQjbUUfdGZe9SytkhDn/s2jjHFDFoVgxjgArZNGI8ZFxHOD7AoZQDSKGHdLrF31YtblP5sVyEEnhFoqiANGfm5siMWMD9HekAu50HXUfhuZnM8bvx3WHOdHgNAXh+Ei8gtXflp/kmbXUQmes3C39sezwjKSAerPA=
  file: /tmp/wdxtaglib/wdx_WDXTagLib_*.zip
  on:
    repo: murzz/wdxtaglib
    tags: true
